from __future__ import annotations


SAMPLE_INCIDENTS = [
    {
        "incident_id": "INC-1001",
        "title": "Santa Fe substation transformer alarm",
        "category": "utility",
        "severity": "high",
        "status": "active",
        "latitude": 35.6932,
        "longitude": -105.9446,
        "summary": "Telemetry indicates heat and load anomalies at a Santa Fe distribution substation.",
    },
    {
        "incident_id": "INC-1002",
        "title": "Espanola feeder line vegetation contact",
        "category": "utility",
        "severity": "medium",
        "status": "monitoring",
        "latitude": 35.9924,
        "longitude": -106.0801,
        "summary": "Field crew reported vegetation contact along a Rio Grande feeder corridor.",
    },
    {
        "incident_id": "INC-1003",
        "title": "Los Alamos canyon access restriction",
        "category": "transportation",
        "severity": "medium",
        "status": "active",
        "latitude": 35.8811,
        "longitude": -106.3047,
        "summary": "Access controls may affect crew routing toward transmission and utility assets.",
    },
    {
        "incident_id": "INC-1004",
        "title": "Taos winter weather outage watch",
        "category": "weather",
        "severity": "medium",
        "status": "monitoring",
        "latitude": 36.4072,
        "longitude": -105.5731,
        "summary": "Winter weather may affect service reliability and field response north of Espanola.",
    },
    {
        "incident_id": "INC-1005",
        "title": "Raton Pass communications site alarm",
        "category": "communications",
        "severity": "high",
        "status": "active",
        "latitude": 36.9031,
        "longitude": -104.4392,
        "summary": "Communications equipment alarm near the Colorado border may affect regional coordination.",
    },
    {
        "incident_id": "INC-1006",
        "title": "Chama feeder patrol request",
        "category": "utility",
        "severity": "low",
        "status": "monitoring",
        "latitude": 36.9036,
        "longitude": -106.5795,
        "summary": "Routine patrol request for a remote feeder corridor near the northern state line.",
    },
    {
        "incident_id": "INC-1007",
        "title": "Mora disaster relief supply staging",
        "category": "disaster_relief",
        "severity": "high",
        "status": "active",
        "latitude": 35.9742,
        "longitude": -105.3294,
        "summary": "Relief supplies and temporary shelter support are staging for isolated communities east of the Sangre de Cristo range.",
    },
    {
        "incident_id": "INC-1008",
        "title": "Red River evacuation route monitoring",
        "category": "disaster_relief",
        "severity": "medium",
        "status": "monitoring",
        "latitude": 36.7081,
        "longitude": -105.4064,
        "summary": "Potential evacuation route constraints require monitoring for relief traffic and public-safety access.",
    },
    {
        "incident_id": "INC-1009",
        "title": "Santa Fe EOC perimeter alarm",
        "category": "force_protection",
        "severity": "high",
        "status": "active",
        "latitude": 35.6896,
        "longitude": -105.9352,
        "summary": "Force-protection alarm near the emergency operations center requires verification before shift turnover.",
    },
    {
        "incident_id": "INC-1010",
        "title": "Raton Pass convoy checkpoint delay",
        "category": "force_protection",
        "severity": "medium",
        "status": "active",
        "latitude": 36.9950,
        "longitude": -104.4788,
        "summary": "Security checkpoint delay may affect escorted logistics movement near the Colorado border.",
    },
]


SAMPLE_ASSETS = [
    {
        "asset_id": "AST-2001",
        "name": "Santa Fe Emergency Operations Center",
        "asset_type": "operations",
        "criticality": "high",
        "latitude": 35.6870,
        "longitude": -105.9378,
    },
    {
        "asset_id": "AST-2002",
        "name": "Los Alamos transmission substation",
        "asset_type": "substation",
        "criticality": "high",
        "latitude": 35.8891,
        "longitude": -106.3050,
    },
    {
        "asset_id": "AST-2003",
        "name": "Espanola switching station",
        "asset_type": "switch",
        "criticality": "medium",
        "latitude": 35.9911,
        "longitude": -106.0806,
    },
    {
        "asset_id": "AST-2004",
        "name": "Taos regional service yard",
        "asset_type": "field_operations",
        "criticality": "medium",
        "latitude": 36.4070,
        "longitude": -105.5733,
    },
    {
        "asset_id": "AST-2005",
        "name": "Raton Pass communications site",
        "asset_type": "communications",
        "criticality": "high",
        "latitude": 36.9028,
        "longitude": -104.4389,
    },
    {
        "asset_id": "AST-2006",
        "name": "Chama distribution substation",
        "asset_type": "substation",
        "criticality": "medium",
        "latitude": 36.9037,
        "longitude": -106.5791,
    },
]
